enemy_list = [
    # Chapter 1: The Call to Adventure (Galador and Surrounding Areas)
    {
        'id': 1,
        'encounter': 'In a dark alley, you encounter a rough-looking individual with a crude weapon. It is a Street Thug, a common criminal lurking in the shadows.',
        "name": "Street Thug",
        "description": "Common criminals lurking in the alleys of Galador.",
        "appearance": "Rough-looking individuals with crude weapons.",
        "abilities": "Quick attacks, can call for backup.",
        "weakness": "Low health, susceptible to strong single attacks.",
        "location": "Galador",
        "chapter": 1,
        "Health": 20,
        "Attack": 5,
        "Defence": 3,
        "Gold": 10,
        "Potion": 1,
        "Elixir": 0
    },
    {
        'id': 2,
        'encounter': 'As you pass a checkpoint, a menacing guard steps forward. It is a Corrupt Guard, exploiting the city\'s chaos.',
        "name": "Corrupt Guard",
        "description": "Guards turned rogue, exploiting the city's chaos.",
        "appearance": "Armored guards with a menacing look.",
        "abilities": "Shield block, heavy melee attacks.",
        "weakness": "Slow, weak to agility-based attacks.",
        "location": "Galador",
        "chapter": 1,
        "Health": 30,
        "Attack": 10,
        "Defence": 5,
        "Gold": 20,
        "Potion": 2,
        "Elixir": 1
    },
    {
        'id': 3,
        'encounter': 'In the bustling market, a shady figure approaches you. It is a Market Swindler, using trickery to rob unsuspecting travelers.',
        "name": "Market Swindler",
        "description": "Deceptive merchants who use trickery to rob.",
        "appearance": "Shady figures with hidden daggers.",
        "abilities": "Stealth attacks, can steal items.",
        "weakness": "Easily overpowered when caught.",
        "location": "Galador",
        "chapter": 1,
        "Health": 25,
        "Attack": 7,
        "Defence": 4,
        "Gold": 15,
        "Potion": 1,
        "Elixir": 1
    },
    {
        'id': 4,
        'encounter': 'Near the city outskirts, a wild dog with foam at its mouth leaps at you. It is a Rabid Dog, driven mad by a mysterious illness.',
        "name": "Rabid Dog",
        "description": "Stray dogs affected by a mysterious illness.",
        "appearance": "Wild, foaming at the mouth.",
        "abilities": "Quick bites, can cause bleeding.",
        "weakness": "Low defense, easily scared.",
        "location": "Galador",
        "chapter": 1,
        "Health": 15,
        "Attack": 5,
        "Defence": 2,
        "Gold": 5,
        "Potion": 1,
        "Elixir": 0
    },

    # Chapter 2: The Path of Trials (Enchanted Forest)
    {
        'id': 5,
        'encounter': 'After walking out of the city gates, you encounter a massive figure made of stone and metal with glowing runes. It is a Stone Sentinel, an ancient golem created to guard Thaemus.',
        "name": "Stone Sentinel",
        "description": "Ancient golems created to guard Thaemus, now crushing intruders.",
        "appearance": "Massive figures made of stone and metal with glowing runes.",
        "abilities": "Immense strength, hurl boulders, create seismic shockwaves.",
        "weakness": "Slow, susceptible to agility-based attacks and magic disrupting runes.",
        "location": "Enchanted Forest",
        "chapter": 2,
        "Health": 40,
        "Attack": 10,
        "Defence": 5,
        "Gold": 20,
        "Potion": 2,
        "Elixir": 1
    },
    {
        'id': 6,
        "encounter": "After defeating the Stone Sentinel, you walked onto a path and see a hooded figure with glowing eyes. It is an Arcane Trickster, a rogue mage using forbidden magic to deceive and trap adventurers.",
        "name": "Arcane Trickster",
        "description": "Rogue mages using forbidden magic, deceiving and trapping adventurers.",
        "appearance": "Hooded figures with glowing eyes, adorned with talismans.",
        "abilities": "Illusions, powerful spells, magical traps, summon spectral minions.",
        "weakness": "Overconfidence, illusions dispelled with clarity spells.",
        "location": "Enchanted Forest",
        "chapter": 2,
        "Health": 50,
        "Attack": 15,
        "Defence": 6,
        "Gold": 40,
        "Potion": 3,
        "Elixir": 2
    },
    {
        'id': 7,
        "encounter": "After defeating the Arcane Trickster, you walked into a clearing and see ghostly figures floating among the ruins. They are Shadow Wraiths, ghostly remnants of Thaemus's cursed inhabitants, haunting the ruins.",
        "name": "Shadow Wraith",
        "description": "Ghostly remnants of Thaemus's cursed inhabitants, haunting the ruins.",
        "appearance": "Ghostly figures with glowing eyes and tattered cloaks.",
        "abilities": "Phase through walls, become invisible, drain life force.",
        "weakness": "Vulnerable to light-based magic and enchanted weapons.",
        "location": "Enchanted Forest",
        "chapter": 2,
        "Health": 60,
        "Attack": 20,
        "Defence": 7,
        "Gold": 50,
        "Potion": 4,
        "Elixir": 3
    },
    {
        'id': 8,
        "encounter": "After defeating the Shadow Wraiths, you entered a dense forest and hear rustling in the trees. A sleek, feline-like creature with mottled fur and piercing eyes emerges. It is a Forest Stalker, a predatory creature that camouflages and ambushes travelers in the forests.",
        "name": "Forest Stalker",
        "description": "Predatory creatures that camouflage and ambush travelers in the forests.",
        "appearance": "Sleek, feline-like with mottled fur, sharp claws, piercing eyes.",
        "abilities": "Stealth, climb trees, paralyzing bite.",
        "weakness": "Vulnerable to fire and loud noises.",
        "location": "Enchanted Forest",
        "chapter": 2,
        "Health": 70,
        "Attack": 25,
        "Defence": 7,
        "Gold": 60,
        "Potion": 5,
        "Elixir": 4
    },

    # Chapter 3: The Lost City (Treacherous Mountains)
    {
        'id': 9,
        'encounter': 'As you climb the mountain, a boulder suddenly shifts and stands up. It is a Rock Golem, ready to defend its territory.',
        "name": "Rock Golem",
        "description": "Stone creatures that blend into the mountain terrain.",
        "appearance": "Massive, rocky forms with glowing eyes.",
        "abilities": "Throw rocks, create tremors.",
        "weakness": "Susceptible to water and ice.",
        "location": "Treacherous Mountains",
        "chapter": 3,
        "Health": 50,
        "Attack": 20,
        "Defence": 10,
        "Gold": 30,
        "Potion": 3,
        "Elixir": 2
    },
    {
        'id': 10,
        'encounter': 'A rugged figure blocks your path. It is a Mountain Bandit, looking to steal from travelers.',
        "name": "Mountain Bandit",
        "description": "Outlaws who have taken refuge in the mountains.",
        "appearance": "Rough, weather-beaten with a menacing look.",
        "abilities": "Quick strikes, can set traps.",
        "weakness": "Low defense, weak to ranged attacks.",
        "location": "Treacherous Mountains",
        "chapter": 3,
        "Health": 30,
        "Attack": 10,
        "Defence": 4,
        "Gold": 20,
        "Potion": 2,
        "Elixir": 1
    },
    {
        'id': 11,
        'encounter': 'A chilling wind blows as a serpentine figure emerges from the snow. It is an Ice Wyrm, guardian of the frozen peaks.',
        "name": "Ice Wyrm",
        "description": "Serpentine creatures that dwell in the snowy peaks.",
        "appearance": "Long, white scales with icy breath.",
        "abilities": "Ice breath, burrow through snow.",
        "weakness": "Weak to fire and heat.",
        "location": "Treacherous Mountains",
        "chapter": 3,
        "Health": 45,
        "Attack": 15,
        "Defence": 8,
        "Gold": 25,
        "Potion": 2,
        "Elixir": 1
    },
    {
        'id': 12,
        'encounter': 'You hear a thunderous roar and see a winged beast swooping down. It is a Thunder Roc, a giant bird that commands lightning.',
        "name": "Thunder Roc",
        "description": "Giant birds that control storms and lightning.",
        "appearance": "Massive wings, crackling with electricity.",
        "abilities": "Lightning strikes, powerful talons.",
        "weakness": "Weak to wind and ranged attacks.",
        "location": "Treacherous Mountains",
        "chapter": 3,
        "Health": 55,
        "Attack": 20,
        "Defence": 9,
        "Gold": 30,
        "Potion": 3,
        "Elixir": 2
    },

    # Chapter 4: The Final Confrontation (Ruins of Thaemus)
    {
        'id': 13,
        'encounter': 'In the heart of the ruins, you face a towering figure of dark energy. It is a Void Guardian, the final protector of the artifact.',
        "name": "Void Guardian",
        "description": "Powerful beings of dark energy that guard the artifact.",
        "appearance": "Tall, shadowy figures with a malevolent aura.",
        "abilities": "Dark magic, life drain.",
        "weakness": "Weak to light and holy magic.",
        "location": "Ruins of Thaemus",
        "chapter": 4,
        "Health": 60,
        "Attack": 25,
        "Defence": 10,
        "Gold": 50,
        "Potion": 4,
        "Elixir": 3
    },
    {
        'id': 14,
        'encounter': 'As you explore the ruins, you encounter a spectral figure. It is a Phantom Warrior, a ghostly knight bound to protect Thaemus.',
        "name": "Phantom Warrior",
        "description": "Ghostly knights that protect the ruins.",
        "appearance": "Spectral knights with glowing swords.",
        "abilities": "Spectral blade, phase through attacks.",
        "weakness": "Weak to enchanted weapons.",
        "location": "Ruins of Thaemus",
        "chapter": 4,
        "Health": 45,
        "Attack": 20,
        "Defence": 7,
        "Gold": 40,
        "Potion": 3,
        "Elixir": 2
    },
    {
        'id': 15,
        'encounter': 'From the shadows emerges a creature with glowing red eyes. It is a Night Stalker, a deadly predator of the ruins.',
        "name": "Night Stalker",
        "description": "Stealthy predators that hunt in the dark ruins.",
        "appearance": "Shadowy creatures with glowing red eyes.",
        "abilities": "Stealth attacks, poison claws.",
        "weakness": "Weak to light and fire.",
        "location": "Ruins of Thaemus",
        "chapter": 4,
        "Health": 50,
        "Attack": 20,
        "Defence": 8,
        "Gold": 45,
        "Potion": 3,
        "Elixir": 2
    },
    {
        'id': 16,
        'encounter': 'A massive skeletal figure rises from the ground. It is a Bone Colossus, an ancient guardian of the ruins.',
        "name": "Bone Colossus",
        "description": "Giant skeletons that guard the ancient ruins.",
        "appearance": "Massive skeletons with ancient armor.",
        "abilities": "Bone crush, summon skeletal minions.",
        "weakness": "Weak to blunt weapons and fire.",
        "location": "Ruins of Thaemus",
        "chapter": 4,
        "Health": 55,
        "Attack": 22,
        "Defence": 9,
        "Gold": 50,
        "Potion": 4,
        "Elixir": 3
    }
]

chapter_1_enemies = [enemy for enemy in enemy_list if enemy['chapter'] == 1]
chapter_2_enemies = [enemy for enemy in enemy_list if enemy['chapter'] == 2]
chapter_3_enemies = [enemy for enemy in enemy_list if enemy['chapter'] == 3]
chapter_4_enemies = [enemy for enemy in enemy_list if enemy['chapter'] == 4]